from __future__ import annotations

import json
import os
import shlex
import signal
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .models import BenchmarkAnswer, ResearchResponse


class ProviderError(RuntimeError):
    pass


@dataclass
class ProviderTask:
    task_type: str
    instructions: str
    payload: dict[str, Any]

    def to_dict(self) -> dict[str, Any]:
        return {
            "task_type": self.task_type,
            "instructions": self.instructions,
            "payload": self.payload,
        }


class BaseProvider:
    def invoke(self, task: ProviderTask) -> dict[str, Any]:
        raise NotImplementedError


class MockProvider(BaseProvider):
    def invoke(self, task: ProviderTask) -> dict[str, Any]:
        if task.task_type == "research_iteration":
            return self._research_iteration(task.payload)
        if task.task_type == "judge_evaluation":
            return self._judge_evaluation(task.payload)
        raise ProviderError(f"Unsupported mock task type: {task.task_type}")

    def _research_iteration(self, payload: dict[str, Any]) -> dict[str, Any]:
        topic = payload["topic"]
        iteration = int(payload["state"]["iteration"]) + 1
        sources = payload.get("sources", [])
        benchmark = payload.get("benchmark", [])
        current_knowledge = payload.get("knowledge_base_markdown", "").strip()

        source_sections: list[str] = []
        for source in sources:
            content = " ".join(source["content"].split())
            source_sections.append(f"- {source['id']}: {content[:220]}")

        answers: list[BenchmarkAnswer] = []
        for item in benchmark:
            must_include = item.get("must_include", [])
            required_sources = item.get("required_sources", [])
            citations = required_sources or ([sources[0]["id"]] if sources else [])
            answer_parts = [
                f"For benchmark {item['id']}, the key explanation is grounded in the run sources."
            ]
            if must_include:
                answer_parts.append(
                    "Required details: " + ", ".join(must_include) + "."
                )
            if citations:
                answer_parts.append(
                    "Cited evidence: " + ", ".join(citations) + "."
                )
            answers.append(
                BenchmarkAnswer(
                    id=item["id"],
                    answer=" ".join(answer_parts),
                    citations=citations,
                )
            )

        source_summary = "\n".join(source_sections) if source_sections else "- No sources loaded yet."
        lines = [
            "# Knowledge Base",
            "",
            f"Topic: {topic}",
            "",
            f"Iteration: {iteration}",
            "",
            "## Current Synthesis",
            "This knowledge base summarizes the current best understanding from the frozen source set.",
            "",
            "## Source Notes",
            source_summary,
            "",
            "## Benchmark-Oriented Takeaways",
        ]
        knowledge_base = "\n".join(lines).rstrip()

        for answer in answers:
            knowledge_base += (
                f"\n\n### {answer.id}\n"
                f"{answer.answer}\n"
                f"Citations: {', '.join(answer.citations) if answer.citations else 'none'}"
            )

        if current_knowledge and "Iteration:" not in current_knowledge:
            knowledge_base += "\n\n## Prior Context\n" + current_knowledge

        response = ResearchResponse(
            experiment_title=f"iteration-{iteration}-mock-synthesis",
            change_summary="Generate a benchmark-oriented synthesis from the fixed sources.",
            knowledge_base_markdown=knowledge_base,
            benchmark_answers=answers,
            notes=["Generated by the built-in mock provider."],
        )
        return response.to_dict()

    def _judge_evaluation(self, payload: dict[str, Any]) -> dict[str, Any]:
        """Generate a mock judge evaluation response.

        Reads the configured dimensions from the task payload and returns
        reasonable scores for each dimension.
        """
        goal_state = payload.get("goal_state", {})
        dimensions = goal_state.get("dimensions", [])

        # Generate scores for each configured dimension
        # Use a deterministic pattern: 6-8 range for mock scores
        dimension_scores: dict[str, int] = {}
        base_score = 7
        for i, dim in enumerate(dimensions):
            name = dim.get("name", f"dim_{i}")
            # Alternate between 6 and 8 for variety
            dimension_scores[name] = base_score + (1 if i % 2 == 0 else -1)

        # Identify the lowest-scoring dimension as priority
        if dimension_scores:
            priority_dimension = min(dimension_scores, key=dimension_scores.get)  # type: ignore[arg-type]
        else:
            priority_dimension = "unknown"

        return {
            "dimension_scores": dimension_scores,
            "review_markdown": "Mock judge review: candidate shows adequate coverage with room for improvement.",
            "priority_dimension": priority_dimension,
            "improvement_suggestion": "Add more specific evidence and citations to strengthen claims.",
        }


class CommandProvider(BaseProvider):
    def __init__(self, command: str, cwd: Path | None = None) -> None:
        if not command.strip():
            raise ProviderError("Command provider requires a non-empty command.")
        self.command = command
        self.cwd = cwd

    def invoke(self, task: ProviderTask) -> dict[str, Any]:
        completed = subprocess.run(
            shlex.split(self.command),
            input=json.dumps(task.to_dict()),
            text=True,
            capture_output=True,
            cwd=str(self.cwd) if self.cwd else None,
            check=False,
        )
        if completed.returncode != 0:
            raise ProviderError(
                "Command provider failed with exit code "
                f"{completed.returncode}: {completed.stderr.strip()}"
            )
        stdout = completed.stdout.strip()
        if not stdout:
            raise ProviderError("Command provider returned empty stdout.")
        try:
            return json.loads(stdout)
        except json.JSONDecodeError as exc:
            raise ProviderError(f"Command provider returned invalid JSON: {exc}") from exc


def _load_default_timeout() -> int:
    raw = os.getenv("LLM_AUTORESEARCH_CLI_TIMEOUT_SECONDS", "").strip()
    if not raw:
        return 600
    try:
        return int(raw)
    except ValueError:
        return 600


_DEFAULT_TIMEOUT = _load_default_timeout()


class CliAgentProvider(BaseProvider):
    """Provider that spawns a CLI agent (codex, claude, etc.) via subprocess.

    The provider writes the task JSON to a temp file, builds the command from
    cli_binary + cli_flags + prompt content, and parses JSON from stdout.

    Uses subprocess.Popen with process group management (os.setsid / os.killpg)
    to ensure child processes are terminated on timeout.
    """

    def __init__(
        self,
        cli_binary: str,
        cli_flags: str = "",
        role: str = "producer",
        timeout: int | None = None,
    ) -> None:
        self.cli_binary = cli_binary
        self.cli_flags = cli_flags
        self.role = role
        self.timeout = timeout if timeout is not None else _DEFAULT_TIMEOUT

    def invoke(self, task: ProviderTask) -> dict[str, Any]:
        prompt_content = json.dumps(task.to_dict(), indent=2)
        if Path(self.cli_binary).name == "codex":
            return self._invoke_codex(prompt_content)

        stdout, stderr, returncode = self._run_process(
            [self.cli_binary] + shlex.split(self.cli_flags) + ["-"],
            prompt_content,
        )
        if returncode != 0:
            raise ProviderError(
                f"CLI agent exited with code {returncode}: "
                f"{stderr.strip() if stderr else '(no stderr)'}"
            )
        return self._extract_json(stdout)

    def _invoke_codex(self, prompt_content: str) -> dict[str, Any]:
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".json", delete=False
        ) as tmp:
            output_file = tmp.name

        try:
            stdout, stderr, returncode = self._run_process(
                [
                    self.cli_binary,
                    *shlex.split(self.cli_flags),
                    "--output-last-message",
                    output_file,
                    "-",
                ],
                prompt_content,
            )
            if returncode != 0:
                raise ProviderError(
                    f"CLI agent exited with code {returncode}: "
                    f"{stderr.strip() if stderr else '(no stderr)'}"
                )

            output_text = Path(output_file).read_text(encoding="utf-8").strip()
            if not output_text:
                raise ProviderError(
                    "Codex CLI completed without writing the final message payload."
                )
            return self._extract_json(output_text)
        finally:
            try:
                os.unlink(output_file)
            except OSError:
                pass

    def _run_process(
        self,
        cmd_parts: list[str],
        prompt_content: str,
    ) -> tuple[str, str, int]:
        try:
            proc = subprocess.Popen(
                cmd_parts,
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                preexec_fn=os.setsid,
            )
        except FileNotFoundError as exc:
            raise ProviderError(
                f"CLI binary not found: {self.cli_binary}"
            ) from exc
        except OSError as exc:
            raise ProviderError(
                f"Failed to spawn CLI process: {exc}"
            ) from exc

        try:
            stdout, stderr = proc.communicate(
                input=prompt_content, timeout=self.timeout
            )
        except subprocess.TimeoutExpired:
            try:
                os.killpg(os.getpgid(proc.pid), signal.SIGTERM)
            except OSError:
                proc.kill()
            try:
                proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                proc.kill()
                proc.wait(timeout=5)
            raise ProviderError(
                f"CLI agent timeout after {self.timeout}s: {self.cli_binary}"
            )
        finally:
            for pipe in (proc.stdout, proc.stderr):
                if pipe is not None:
                    try:
                        pipe.close()
                    except OSError:
                        pass

        return stdout, stderr, proc.returncode

    @staticmethod
    def _extract_json(stdout: str) -> dict[str, Any]:
        try:
            parsed = json.loads(stdout)
        except json.JSONDecodeError:
            brace_idx = stdout.find("{")
            if brace_idx == -1:
                raise ProviderError(
                    "CLI agent stdout contains no JSON object. "
                    f"Output: {stdout[:200]}"
                )
            json_str = stdout[brace_idx:]
            try:
                parsed, _ = json.JSONDecoder().raw_decode(json_str)
            except json.JSONDecodeError as exc:
                raise ProviderError(
                    f"CLI agent returned invalid JSON: {exc}. "
                    f"Raw output (from first brace): {json_str[:200]}"
                ) from exc

        return CliAgentProvider._coerce_json_payload(parsed)

    @staticmethod
    def _coerce_json_payload(parsed: Any) -> dict[str, Any]:
        if isinstance(parsed, dict):
            return parsed

        if isinstance(parsed, str):
            try:
                nested = json.loads(parsed)
            except json.JSONDecodeError as exc:
                raise ProviderError(
                    "CLI agent returned a string that is not valid JSON: "
                    f"{parsed[:200]}"
                ) from exc
            return CliAgentProvider._coerce_json_payload(nested)

        if isinstance(parsed, list):
            for item in reversed(parsed):
                if not isinstance(item, dict):
                    continue

                result = item.get("result")
                if isinstance(result, dict):
                    return result
                if isinstance(result, str):
                    try:
                        nested = json.loads(result)
                    except json.JSONDecodeError:
                        nested = None
                    if isinstance(nested, dict):
                        return nested

                message = item.get("message")
                if isinstance(message, dict):
                    content = message.get("content")
                    if isinstance(content, list):
                        for block in reversed(content):
                            if not isinstance(block, dict):
                                continue
                            text = block.get("text")
                            if not isinstance(text, str):
                                continue
                            try:
                                nested = json.loads(text)
                            except json.JSONDecodeError:
                                continue
                            if isinstance(nested, dict):
                                return nested

            raise ProviderError(
                "CLI agent returned a JSON array but no dict payload could be extracted."
            )

        raise ProviderError(
            "CLI agent returned JSON that is not an object. "
            f"Type: {type(parsed).__name__}"
        )


# Pre-configured CLI agent patterns
_CLI_PRESETS: dict[str, tuple[str, str]] = {
    "codex": ("codex", "exec --dangerously-bypass-approvals-and-sandbox"),
    "claude": ("claude", "-p --dangerously-skip-permissions"),
}


def create_provider(
    kind: str,
    command: str = "",
    cwd: Path | None = None,
    cli_binary: str = "",
    cli_flags: str = "",
    role: str = "producer",
    timeout: int | None = None,
) -> BaseProvider:
    normalized = kind.strip().lower()
    if normalized == "mock":
        return MockProvider()
    if normalized == "command":
        return CommandProvider(command=command, cwd=cwd)
    if normalized in _CLI_PRESETS:
        preset_binary, preset_flags = _CLI_PRESETS[normalized]
        return CliAgentProvider(
            cli_binary=cli_binary or preset_binary,
            cli_flags=cli_flags or preset_flags,
            role=role,
            timeout=timeout,
        )
    if normalized == "cli":
        return CliAgentProvider(
            cli_binary=cli_binary,
            cli_flags=cli_flags,
            role=role,
            timeout=timeout,
        )
    raise ProviderError(f"Unsupported provider kind: {kind}")
