from __future__ import annotations

import json
import shlex
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .models import BenchmarkAnswer, ResearchResponse


class ProviderError(RuntimeError):
    pass


@dataclass
class ProviderTask:
    task_type: str
    instructions: str
    payload: dict[str, Any]

    def to_dict(self) -> dict[str, Any]:
        return {
            "task_type": self.task_type,
            "instructions": self.instructions,
            "payload": self.payload,
        }


class BaseProvider:
    def invoke(self, task: ProviderTask) -> dict[str, Any]:
        raise NotImplementedError


class MockProvider(BaseProvider):
    def invoke(self, task: ProviderTask) -> dict[str, Any]:
        if task.task_type != "research_iteration":
            raise ProviderError(f"Unsupported mock task type: {task.task_type}")
        return self._research_iteration(task.payload)

    def _research_iteration(self, payload: dict[str, Any]) -> dict[str, Any]:
        topic = payload["topic"]
        iteration = int(payload["state"]["iteration"]) + 1
        sources = payload.get("sources", [])
        benchmark = payload.get("benchmark", [])
        current_knowledge = payload.get("knowledge_base_markdown", "").strip()

        source_sections: list[str] = []
        for source in sources:
            content = " ".join(source["content"].split())
            source_sections.append(f"- {source['id']}: {content[:220]}")

        answers: list[BenchmarkAnswer] = []
        for item in benchmark:
            must_include = item.get("must_include", [])
            required_sources = item.get("required_sources", [])
            citations = required_sources or ([sources[0]["id"]] if sources else [])
            answer_parts = [
                f"For benchmark {item['id']}, the key explanation is grounded in the run sources."
            ]
            if must_include:
                answer_parts.append(
                    "Required details: " + ", ".join(must_include) + "."
                )
            if citations:
                answer_parts.append(
                    "Cited evidence: " + ", ".join(citations) + "."
                )
            answers.append(
                BenchmarkAnswer(
                    id=item["id"],
                    answer=" ".join(answer_parts),
                    citations=citations,
                )
            )

        source_summary = "\n".join(source_sections) if source_sections else "- No sources loaded yet."
        lines = [
            "# Knowledge Base",
            "",
            f"Topic: {topic}",
            "",
            f"Iteration: {iteration}",
            "",
            "## Current Synthesis",
            "This knowledge base summarizes the current best understanding from the frozen source set.",
            "",
            "## Source Notes",
            source_summary,
            "",
            "## Benchmark-Oriented Takeaways",
        ]
        knowledge_base = "\n".join(lines).rstrip()

        for answer in answers:
            knowledge_base += (
                f"\n\n### {answer.id}\n"
                f"{answer.answer}\n"
                f"Citations: {', '.join(answer.citations) if answer.citations else 'none'}"
            )

        if current_knowledge and "Iteration:" not in current_knowledge:
            knowledge_base += "\n\n## Prior Context\n" + current_knowledge

        response = ResearchResponse(
            experiment_title=f"iteration-{iteration}-mock-synthesis",
            change_summary="Generate a benchmark-oriented synthesis from the fixed sources.",
            knowledge_base_markdown=knowledge_base,
            benchmark_answers=answers,
            notes=["Generated by the built-in mock provider."],
        )
        return response.to_dict()


class CommandProvider(BaseProvider):
    def __init__(self, command: str, cwd: Path | None = None) -> None:
        if not command.strip():
            raise ProviderError("Command provider requires a non-empty command.")
        self.command = command
        self.cwd = cwd

    def invoke(self, task: ProviderTask) -> dict[str, Any]:
        completed = subprocess.run(
            shlex.split(self.command),
            input=json.dumps(task.to_dict()),
            text=True,
            capture_output=True,
            cwd=str(self.cwd) if self.cwd else None,
            check=False,
        )
        if completed.returncode != 0:
            raise ProviderError(
                "Command provider failed with exit code "
                f"{completed.returncode}: {completed.stderr.strip()}"
            )
        stdout = completed.stdout.strip()
        if not stdout:
            raise ProviderError("Command provider returned empty stdout.")
        try:
            return json.loads(stdout)
        except json.JSONDecodeError as exc:
            raise ProviderError(f"Command provider returned invalid JSON: {exc}") from exc


def create_provider(kind: str, command: str = "", cwd: Path | None = None) -> BaseProvider:
    normalized = kind.strip().lower()
    if normalized == "mock":
        return MockProvider()
    if normalized == "command":
        return CommandProvider(command=command, cwd=cwd)
    raise ProviderError(f"Unsupported provider kind: {kind}")
