from __future__ import annotations

import json
import os
import shlex
import signal
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .models import BenchmarkAnswer, ResearchResponse


class ProviderError(RuntimeError):
    pass


@dataclass
class ProviderTask:
    task_type: str
    instructions: str
    payload: dict[str, Any]

    def to_dict(self) -> dict[str, Any]:
        return {
            "task_type": self.task_type,
            "instructions": self.instructions,
            "payload": self.payload,
        }


class BaseProvider:
    def invoke(self, task: ProviderTask) -> dict[str, Any]:
        raise NotImplementedError


class MockProvider(BaseProvider):
    def invoke(self, task: ProviderTask) -> dict[str, Any]:
        if task.task_type != "research_iteration":
            raise ProviderError(f"Unsupported mock task type: {task.task_type}")
        return self._research_iteration(task.payload)

    def _research_iteration(self, payload: dict[str, Any]) -> dict[str, Any]:
        topic = payload["topic"]
        iteration = int(payload["state"]["iteration"]) + 1
        sources = payload.get("sources", [])
        benchmark = payload.get("benchmark", [])
        current_knowledge = payload.get("knowledge_base_markdown", "").strip()

        source_sections: list[str] = []
        for source in sources:
            content = " ".join(source["content"].split())
            source_sections.append(f"- {source['id']}: {content[:220]}")

        answers: list[BenchmarkAnswer] = []
        for item in benchmark:
            must_include = item.get("must_include", [])
            required_sources = item.get("required_sources", [])
            citations = required_sources or ([sources[0]["id"]] if sources else [])
            answer_parts = [
                f"For benchmark {item['id']}, the key explanation is grounded in the run sources."
            ]
            if must_include:
                answer_parts.append(
                    "Required details: " + ", ".join(must_include) + "."
                )
            if citations:
                answer_parts.append(
                    "Cited evidence: " + ", ".join(citations) + "."
                )
            answers.append(
                BenchmarkAnswer(
                    id=item["id"],
                    answer=" ".join(answer_parts),
                    citations=citations,
                )
            )

        source_summary = "\n".join(source_sections) if source_sections else "- No sources loaded yet."
        lines = [
            "# Knowledge Base",
            "",
            f"Topic: {topic}",
            "",
            f"Iteration: {iteration}",
            "",
            "## Current Synthesis",
            "This knowledge base summarizes the current best understanding from the frozen source set.",
            "",
            "## Source Notes",
            source_summary,
            "",
            "## Benchmark-Oriented Takeaways",
        ]
        knowledge_base = "\n".join(lines).rstrip()

        for answer in answers:
            knowledge_base += (
                f"\n\n### {answer.id}\n"
                f"{answer.answer}\n"
                f"Citations: {', '.join(answer.citations) if answer.citations else 'none'}"
            )

        if current_knowledge and "Iteration:" not in current_knowledge:
            knowledge_base += "\n\n## Prior Context\n" + current_knowledge

        response = ResearchResponse(
            experiment_title=f"iteration-{iteration}-mock-synthesis",
            change_summary="Generate a benchmark-oriented synthesis from the fixed sources.",
            knowledge_base_markdown=knowledge_base,
            benchmark_answers=answers,
            notes=["Generated by the built-in mock provider."],
        )
        return response.to_dict()


class CommandProvider(BaseProvider):
    def __init__(self, command: str, cwd: Path | None = None) -> None:
        if not command.strip():
            raise ProviderError("Command provider requires a non-empty command.")
        self.command = command
        self.cwd = cwd

    def invoke(self, task: ProviderTask) -> dict[str, Any]:
        completed = subprocess.run(
            shlex.split(self.command),
            input=json.dumps(task.to_dict()),
            text=True,
            capture_output=True,
            cwd=str(self.cwd) if self.cwd else None,
            check=False,
        )
        if completed.returncode != 0:
            raise ProviderError(
                "Command provider failed with exit code "
                f"{completed.returncode}: {completed.stderr.strip()}"
            )
        stdout = completed.stdout.strip()
        if not stdout:
            raise ProviderError("Command provider returned empty stdout.")
        try:
            return json.loads(stdout)
        except json.JSONDecodeError as exc:
            raise ProviderError(f"Command provider returned invalid JSON: {exc}") from exc


_DEFAULT_TIMEOUT = 300  # 5 minutes


class CliAgentProvider(BaseProvider):
    """Provider that spawns a CLI agent (codex, claude, etc.) via subprocess.

    The provider writes the task JSON to a temp file, builds the command from
    cli_binary + cli_flags + prompt content, and parses JSON from stdout.

    Uses subprocess.Popen with process group management (os.setsid / os.killpg)
    to ensure child processes are terminated on timeout.
    """

    def __init__(
        self,
        cli_binary: str,
        cli_flags: str = "",
        role: str = "producer",
        timeout: int = _DEFAULT_TIMEOUT,
    ) -> None:
        self.cli_binary = cli_binary
        self.cli_flags = cli_flags
        self.role = role
        self.timeout = timeout

    def invoke(self, task: ProviderTask) -> dict[str, Any]:
        prompt_content = json.dumps(task.to_dict(), indent=2)

        # Build command: cli_binary + cli_flags (split) + prompt_content
        cmd_parts = [self.cli_binary] + shlex.split(self.cli_flags) + [prompt_content]

        try:
            proc = subprocess.Popen(
                cmd_parts,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                preexec_fn=os.setsid,
            )
        except FileNotFoundError as exc:
            raise ProviderError(
                f"CLI binary not found: {self.cli_binary}"
            ) from exc
        except OSError as exc:
            raise ProviderError(
                f"Failed to spawn CLI process: {exc}"
            ) from exc

        try:
            stdout, stderr = proc.communicate(timeout=self.timeout)
        except subprocess.TimeoutExpired:
            # Kill entire process group to ensure child processes are also terminated
            try:
                os.killpg(os.getpgid(proc.pid), signal.SIGTERM)
            except OSError:
                proc.kill()
            proc.wait()
            raise ProviderError(
                f"CLI agent timeout after {self.timeout}s: {self.cli_binary}"
            )

        if proc.returncode != 0:
            raise ProviderError(
                f"CLI agent exited with code {proc.returncode}: "
                f"{stderr.strip() if stderr else '(no stderr)'}"
            )

        return self._extract_json(stdout)

    @staticmethod
    def _extract_json(stdout: str) -> dict[str, Any]:
        """Find the first '{' in stdout and parse JSON from there.

        This handles CLI tools that emit non-JSON preamble (status messages,
        progress indicators) before the actual JSON output.
        """
        brace_idx = stdout.find("{")
        if brace_idx == -1:
            raise ProviderError(
                "CLI agent stdout contains no JSON object. "
                f"Output: {stdout[:200]}"
            )
        json_str = stdout[brace_idx:]
        try:
            return json.loads(json_str)
        except json.JSONDecodeError as exc:
            raise ProviderError(
                f"CLI agent returned invalid JSON: {exc}. "
                f"Raw output (from first brace): {json_str[:200]}"
            ) from exc


def create_provider(
    kind: str,
    command: str = "",
    cwd: Path | None = None,
    cli_binary: str = "",
    cli_flags: str = "",
    role: str = "producer",
) -> BaseProvider:
    normalized = kind.strip().lower()
    if normalized == "mock":
        return MockProvider()
    if normalized == "command":
        return CommandProvider(command=command, cwd=cwd)
    if normalized == "cli":
        return CliAgentProvider(
            cli_binary=cli_binary,
            cli_flags=cli_flags,
            role=role,
        )
    raise ProviderError(f"Unsupported provider kind: {kind}")
